[build]
  base = "client"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_FIREBASE_API_KEY = "AIzaSyAna8fTgo9iMZBYBWDuVuW1iJIBWlDpPZI"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "sprint-planning-app-5c655.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "sprint-planning-app-5c655"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "sprint-planning-app-5c655.firebasestorage.app"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "1017106301522"
  REACT_APP_FIREBASE_APP_ID = "1:1017106301522:web:6ead796d5bb4c76322958b"
  
  # Firebase Admin SDK (for Netlify Functions)
  FIREBASE_PROJECT_ID = "sprint-planning-app-5c655"
  FIREBASE_PRIVATE_KEY_ID = "your-private-key-id"
  FIREBASE_PRIVATE_KEY = "your-private-key"
  FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-xxxxx@sprint-planning-app-5c655.iam.gserviceaccount.com"
  FIREBASE_CLIENT_ID = "your-client-id"

[context.deploy-preview.environment]
  REACT_APP_FIREBASE_API_KEY = "AIzaSyAna8fTgo9iMZBYBWDuVuW1iJIBWlDpPZI"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "sprint-planning-app-5c655.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "sprint-planning-app-5c655"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "sprint-planning-app-5c655.firebasestorage.app"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "1017106301522"
  REACT_APP_FIREBASE_APP_ID = "1:1017106301522:web:6ead796d5bb4c76322958b"
  
  # Firebase Admin SDK (for Netlify Functions)
  FIREBASE_PROJECT_ID = "sprint-planning-app-5c655"
  FIREBASE_PRIVATE_KEY_ID = "your-private-key-id"
  FIREBASE_PRIVATE_KEY = "your-private-key"
  FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-xxxxx@sprint-planning-app-5c655.iam.gserviceaccount.com"
  FIREBASE_CLIENT_ID = "your-client-id" 