[build]
  base = "client"
  publish = "client/build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://your-project-id-default-rtdb.firebaseio.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_FIREBASE_API_KEY = "your-api-key"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "your-project-id.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "your-project-id"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "your-project-id.appspot.com"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "123456789"
  REACT_APP_FIREBASE_APP_ID = "your-app-id"

[context.deploy-preview.environment]
  REACT_APP_FIREBASE_API_KEY = "your-api-key"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "your-project-id.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "your-project-id"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "your-project-id.appspot.com"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "123456789"
  REACT_APP_FIREBASE_APP_ID = "your-app-id" 