[build]
  base = "client"
  publish = "build"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_FIREBASE_API_KEY = "AIzaSyAna8fTgo9iMZBYBWDuVuW1iJIBWlDpPZI"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "sprint-planning-app-5c655.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "sprint-planning-app-5c655"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "sprint-planning-app-5c655.firebasestorage.app"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "1017106301522"
  REACT_APP_FIREBASE_APP_ID = "1:1017106301522:web:6ead796d5bb4c76322958b"
  
  # Firebase Admin SDK credentials will be set in Netlify dashboard environment variables
  # FIREBASE_PROJECT_ID, FIREBASE_PRIVATE_KEY_ID, FIREBASE_PRIVATE_KEY, 
  # FIREBASE_CLIENT_EMAIL, FIREBASE_CLIENT_ID

[context.deploy-preview.environment]
  REACT_APP_FIREBASE_API_KEY = "AIzaSyAna8fTgo9iMZBYBWDuVuW1iJIBWlDpPZI"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "sprint-planning-app-5c655.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "sprint-planning-app-5c655"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "sprint-planning-app-5c655.firebasestorage.app"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "1017106301522"
  REACT_APP_FIREBASE_APP_ID = "1:1017106301522:web:6ead796d5bb4c76322958b"
  
  # Firebase Admin SDK credentials will be set in Netlify dashboard environment variables 